package com.example.parser

import androidx.compose.ui.graphics.Color
import com.example.model.SubtitleCue
import com.example.model.SubtitleHorizontalAlign
import com.example.model.SubtitleStyle
import com.example.model.SubtitleVerticalAlign
import java.util.Locale
import kotlin.math.roundToInt

object AssGenerator {

    fun formatAssTimestamp(ms: Long): String {
        val totalSeconds = ms / 1000
        val hours = totalSeconds / 3600
        val minutes = (totalSeconds % 3600) / 60
        val seconds = totalSeconds % 60
        val centiseconds = (ms % 1000) / 10
        return String.format(Locale.US, "%d:%02d:%02d.%02d", hours, minutes, seconds, centiseconds)
    }

    private fun colorToAssHex(color: Color): String {
        val a = ((1f - color.alpha) * 255).roundToInt().coerceIn(0, 255)
        val r = (color.red * 255).roundToInt().coerceIn(0, 255)
        val g = (color.green * 255).roundToInt().coerceIn(0, 255)
        val b = (color.blue * 255).roundToInt().coerceIn(0, 255)
        return String.format(Locale.US, "&H%02X%02X%02X%02X", a, b, g, r)
    }

    fun colorToInlineAssHex(color: Color): String {
        val r = (color.red * 255).roundToInt().coerceIn(0, 255)
        val g = (color.green * 255).roundToInt().coerceIn(0, 255)
        val b = (color.blue * 255).roundToInt().coerceIn(0, 255)
        return String.format(Locale.US, "&H%02X%02X%02X&", b, g, r)
    }

    fun getAssAlignment(vAlign: SubtitleVerticalAlign, hAlign: SubtitleHorizontalAlign): Int {
        return when (vAlign) {
            SubtitleVerticalAlign.TOP -> when (hAlign) {
                SubtitleHorizontalAlign.LEFT -> 7
                SubtitleHorizontalAlign.CENTER -> 8
                SubtitleHorizontalAlign.RIGHT -> 9
            }
            SubtitleVerticalAlign.MIDDLE -> when (hAlign) {
                SubtitleHorizontalAlign.LEFT -> 4
                SubtitleHorizontalAlign.CENTER -> 5
                SubtitleHorizontalAlign.RIGHT -> 6
            }
            SubtitleVerticalAlign.BOTTOM -> when (hAlign) {
                SubtitleHorizontalAlign.LEFT -> 1
                SubtitleHorizontalAlign.CENTER -> 2
                SubtitleHorizontalAlign.RIGHT -> 3
            }
        }
    }

    /**
     * Resolves the font size in ASS coordinate units (PlayRes coordinate system).
     * Aegisub / libass standard: 1:1 with PlayResY resolution.
     */
    fun resolveAssFontSize(fontSizeVal: Float, playResY: Int = 1080): Int {
        // Direct canonical PlayRes font size (standard Aegisub range: 10 to 300)
        return fontSizeVal.roundToInt().coerceIn(10, 300)
    }

    fun generateAss(
        title: String,
        subtitles: List<SubtitleCue>,
        style: SubtitleStyle,
        applyTimeOffset: Boolean = false,
        videoWidth: Int = 1920,
        videoHeight: Int = 1080,
        additionalStyles: List<String> = emptyList(),
        introOffsetMs: Long = 0L
    ): String {
        val sb = StringBuilder()

        val playResX = if (videoWidth > 0) videoWidth else 1920
        val playResY = if (videoHeight > 0) videoHeight else 1080

        // [Script Info]
        sb.appendLine("[Script Info]")
        sb.appendLine("; Script generated by remsubs playground")
        sb.appendLine("; Unified PlayRes coordinate system (1:1 with video frames)")
        sb.appendLine("Title: $title")
        sb.appendLine("ScriptType: v4.00+")
        sb.appendLine("WrapStyle: 0")
        sb.appendLine("ScaledBorderAndShadow: yes")
        sb.appendLine("PlayResX: $playResX")
        sb.appendLine("PlayResY: $playResY")
        sb.appendLine()

        // [V4+ Styles]
        sb.appendLine("[V4+ Styles]")
        sb.appendLine("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding")

        val fontName = style.fontName.ifBlank { "Arial" }
        val fontSize = resolveAssFontSize(style.fontSizeSp, playResY)
        val primaryColour = colorToAssHex(style.textColor)
        val secondaryColour = "&H000000FF"
        val outlineColour = colorToAssHex(style.outlineColor)
        val backColour = colorToAssHex(style.backgroundColor)
        val bold = if (style.isBold) -1 else 0
        val italic = if (style.isItalic) -1 else 0
        val underline = if (style.isUnderline) -1 else 0
        val borderStyle = if (style.hasBackgroundBox) 3 else 1
        val outlineWidth = if (style.hasOutline) style.outlineWidth.roundToInt().coerceAtLeast(1) else 0
        val shadowDepth = if (style.hasOutline) 2 else 0
        val alignment = getAssAlignment(style.verticalAlign, style.horizontalAlign)
        val marginL = style.horizontalPaddingDp.roundToInt().coerceAtLeast(10)
        val marginR = style.horizontalPaddingDp.roundToInt().coerceAtLeast(10)
        val marginV = style.verticalOffsetDp.roundToInt().coerceAtLeast(10)

        sb.appendLine("Style: Default,$fontName,$fontSize,$primaryColour,$secondaryColour,$outlineColour,$backColour,$bold,$italic,$underline,0,100,100,0,0,$borderStyle,$outlineWidth,$shadowDepth,$alignment,$marginL,$marginR,$marginV,1")

        // Include any additional styles defined in original ASS file or cues
        val declaredStyleNames = mutableSetOf("Default", "default")
        for (extraStyleLine in additionalStyles) {
            val trimmed = extraStyleLine.trim()
            if (trimmed.startsWith("Style:", ignoreCase = true)) {
                val parts = trimmed.substring(6).trim().split(",")
                if (parts.isNotEmpty()) {
                    val sName = parts[0].trim()
                    if (sName.isNotEmpty() && !declaredStyleNames.contains(sName.lowercase(Locale.ROOT))) {
                        sb.appendLine(trimmed)
                        declaredStyleNames.add(sName.lowercase(Locale.ROOT))
                    }
                }
            }
        }

        // For any cue with a distinct styleName not yet declared, create a fallback style
        for (cue in subtitles) {
            val sName = cue.styleName.trim()
            if (sName.isNotBlank() && !declaredStyleNames.contains(sName.lowercase(Locale.ROOT))) {
                sb.appendLine("Style: $sName,$fontName,$fontSize,$primaryColour,$secondaryColour,$outlineColour,$backColour,$bold,$italic,$underline,0,100,100,0,0,$borderStyle,$outlineWidth,$shadowDepth,$alignment,$marginL,$marginR,$marginV,1")
                declaredStyleNames.add(sName.lowercase(Locale.ROOT))
            }
        }

        sb.appendLine()

        // [Events]
        sb.appendLine("[Events]")
        sb.appendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text")

        val totalOffset = (if (applyTimeOffset) style.timeOffsetMs else 0L) + introOffsetMs

        for (cue in subtitles.sortedBy { it.startTimeMs }) {
            val startMs = (cue.startTimeMs + totalOffset).coerceAtLeast(0L)
            val endMs = (cue.endTimeMs + totalOffset).coerceAtLeast(startMs)
            val startStr = formatAssTimestamp(startMs)
            val endStr = formatAssTimestamp(endMs)

            // Format dialogue text converting any HTML tags to ASS overrides
            val formattedText = formatCueTextForAss(cue, playResY)
            val layer = cue.layer
            val styleName = if (cue.styleName.isNotBlank()) cue.styleName else "Default"
            val actor = cue.actor
            val marginVVal = cue.marginV

            sb.appendLine("Dialogue: $layer,$startStr,$endStr,$styleName,$actor,0,0,$marginVVal,,$formattedText")
        }

        return sb.toString()
    }

    private fun formatCueTextForAss(cue: SubtitleCue, playResY: Int): String {
        val rawOrClean = if (cue.rawText.isNotBlank()) cue.rawText else cue.cleanText
        // Convert any HTML formatting tags (<i>, <b>, <font>, <br>) to standard ASS override tags
        val baseText = HtmlSubtitleParser.htmlToAss(rawOrClean)
            .replace("\r\n", "\\N")
            .replace("\n", "\\N")

        if (!cue.customPositionEnabled) {
            return baseText
        }

        // Build ASS override tags for this specific cue
        val tags = StringBuilder()
        val customAlign = getAssAlignment(cue.customVerticalAlign, cue.customHorizontalAlign)
        tags.append("\\an$customAlign")

        cue.customFontSizeSp?.let { size ->
            val resolvedSize = resolveAssFontSize(size, playResY)
            tags.append("\\fs$resolvedSize")
        }

        cue.customTextColorArgb?.let { argb ->
            val red = (argb shr 16 and 0xFF)
            val green = (argb shr 8 and 0xFF)
            val blue = (argb and 0xFF)
            val hex = String.format(Locale.US, "&H%02X%02X%02X&", blue, green, red)
            tags.append("\\c$hex")
        }

        cue.customOutlineColorArgb?.let { argb ->
            val red = (argb shr 16 and 0xFF)
            val green = (argb shr 8 and 0xFF)
            val blue = (argb and 0xFF)
            val hex = String.format(Locale.US, "&H%02X%02X%02X&", blue, green, red)
            tags.append("\\3c$hex")
        }

        cue.customIsItalic?.let {
            tags.append(if (it) "\\i1" else "\\i0")
        }

        cue.customIsBold?.let {
            tags.append(if (it) "\\b1" else "\\b0")
        }

        cue.customIsUnderline?.let {
            tags.append(if (it) "\\u1" else "\\u0")
        }

        return "{$tags}$baseText"
    }
}
